name: Development Task
description: Individual development task created from PRD breakdown
title: "[TASK] "
labels: ["task", "ready-for-dev"]
body:
  - type: markdown
    attributes:
      value: |
        ## Development Task
        This task was created from a PRD breakdown and is ready for implementation.

  - type: input
    id: parent-prd
    attributes:
      label: Parent PRD
      description: Link to the original PRD issue
      placeholder: "#123"
    validations:
      required: true

  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: What needs to be implemented?
      placeholder: Detailed description of what needs to be built...
    validations:
      required: true

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
      description: Any specific technical details or approach notes
      placeholder: |
        - Use existing authentication middleware
        - Follow established patterns in /src/auth/
        - Include unit tests

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this task is complete?
      placeholder: |
        - [ ] Feature works as described
        - [ ] Tests written and passing
        - [ ] Code reviewed and approved
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      description: How complex is this task?
      options:
        - Simple (< 4 hours)
        - Medium (4-8 hours)
        - Complex (1-2 days)
        - Epic (> 2 days)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority of this task?
      options:
        - High
        - Medium
        - Low
    validations:
      required: true